services:
  python-api:
    build: .
    network_mode: host  # 使用宿主机网络
    volumes:
      - ./src:/app/src  # 开发时方便修改代码
      - ./data:/app/data  # 如果需要访问数据目录
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_CONTAINER=true  # 标识当前在 Docker 容器中运行
    restart: unless-stopped 